title: Alexon Uthayakumar # your name (or website title) here
logo: "/images/portfolio.png" # your photo (or logo) here
description:
  > # your text below (remove <br> elements if you don't need line breaks)
  The purpose of this blog is to share my thoughts and experiences on various tech topics, including data science, AI, software programming, tools and frameworks, and more.

theme: jekyll-theme-minimal
google_analytics: G-3B0QDYB683 # your Google Analytics tracking ID here

colors:
  crimson: "#900C3F"
